better bash setup for bin/start

diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -1,4 +1,8 @@
-#!/bin/bash
+#!/usr/bin/env bash
+set -o errexit    # always exit on error
+set -o pipefail   # don't ignore exit codes when piping output
+set -o nounset    # fail on unset variables
+
 APP_PATH=/app
 
 proc=$1
